name: PaperModAPI
version: "${version}"
main: de.cjdev.papermodapi.PaperModAPI
bootstrapper: de.cjdev.papermodapi.PaperModAPIBootstrapper
api-version: '1.21'
load: STARTUP
authors: [CJDev]
description: A Modding API for Paper
website: https://modrinth.com/project/paper-mod-api
dependencies:
  server:
    #packetevents:
    #  required: true
    #  load: BEFORE
    DynamicRP:
      required: true
      load: BEFORE
