name: PaperModAPI
version: '1.1'
main: de.cjdev.papermodapi.PaperModAPI
api-version: '1.21'
load: STARTUP
authors: [CJDev]
description: A Modding API for Paper
website: https://modrinth.com/project/paper-mod-api
